local awful = require("awful")
awful.spawn("zsh-patina restart")
awful.spawn.single_instance("firefox-developer-edition")
awful.spawn.single_instance("steam")
awful.spawn.single_instance("env QT_QPA_PLATFORM=xcb QT_QUICK_CONTROLS_STYLE=Material Plex")
awful.spawn.single_instance("discord")
awful.spawn.single_instance("carla ~/.config/carla/default.carxp")
awful.spawn.single_instance("~/bin/minimeters")
awful.spawn.single_instance("ghostty -e metropolis")
