local awful = require("awful")
--awful.spawn.with_shell("pkill carla; carla ~/.config/carla/default.carxp")
awful.spawn.with_shell("zsh-patina restart")
awful.spawn.single_instance("firefox-developer-edition")
awful.spawn.single_instance("steam")
awful.spawn.single_instance("pkill Plex; env QT_QPA_PLATFORM=xcb QT_QUICK_CONTROLS_STYLE=Material Plex")
awful.spawn.single_instance("vesktop")
awful.spawn.single_instance("fooyin")
awful.spawn.with_shell("pkill Rolling\\ Sampler; ".. os.getenv("HOME") .. "/bin/rolling_sampler")
awful.spawn.with_shell("pkill wlsunset; wlsunset -l 37.7 -L -121.4 -t 3500")
awful.spawn.with_shell("pkill MiniMeters; " .. os.getenv("HOME") .. "/bin/minimeters")
awful.spawn.with_shell("sleep 1; dbus-update-activation-environment --systemd --all")
awful.spawn.with_shell("sleep 3; raysession -s Default")
